/* SPDX-FileCopyrightText: © 2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

//! Argument types

pub const gfxd_Word: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Word;
pub const gfxd_Opcode: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Opcode;
pub const gfxd_Coordi: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Coordi;
pub const gfxd_Coordq: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Coordq;
pub const gfxd_Pal: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Pal;
pub const gfxd_Tlut: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tlut;
pub const gfxd_Timg: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Timg;
pub const gfxd_Tmem: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tmem;
pub const gfxd_Tile: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tile;
pub const gfxd_Fmt: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Fmt;
pub const gfxd_Siz: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Siz;
pub const gfxd_Dim: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dim;
pub const gfxd_Cm: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Cm;
pub const gfxd_Tm: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tm;
pub const gfxd_Ts: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ts;
pub const gfxd_Dxt: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dxt;
pub const gfxd_Tag: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tag;
pub const gfxd_Pm: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Pm;
pub const gfxd_Colorpart: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Colorpart;
pub const gfxd_Color: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Color;
pub const gfxd_Lodfrac: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Lodfrac;
pub const gfxd_Cimg: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Cimg;
pub const gfxd_Zimg: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Zimg;
pub const gfxd_Ac: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ac;
pub const gfxd_Ad: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ad;
pub const gfxd_Cd: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Cd;
pub const gfxd_Ccpre: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ccpre;
pub const gfxd_Ccmuxa: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ccmuxa;
pub const gfxd_Ccmuxb: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ccmuxb;
pub const gfxd_Ccmuxc: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ccmuxc;
pub const gfxd_Ccmuxd: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ccmuxd;
pub const gfxd_Acmuxabd: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Acmuxabd;
pub const gfxd_Acmuxc: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Acmuxc;
pub const gfxd_Cv: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Cv;
pub const gfxd_Tc: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tc;
pub const gfxd_Cyc: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Cyc;
pub const gfxd_Zs: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Zs;
pub const gfxd_Ck: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ck;
pub const gfxd_Keyscale: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Keyscale;
pub const gfxd_Keywidth: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Keywidth;
pub const gfxd_Zi: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Zi;
pub const gfxd_Rm1: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Rm1;
pub const gfxd_Rm2: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Rm2;
pub const gfxd_Sc: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Sc;
pub const gfxd_Td: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Td;
pub const gfxd_Tf: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tf;
pub const gfxd_Tl: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tl;
pub const gfxd_Tt: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tt;
pub const gfxd_Tp: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tp;
pub const gfxd_Line: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Line;
pub const gfxd_Vtx: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Vtx;
pub const gfxd_Vtxflag: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Vtxflag;
pub const gfxd_Dl: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dl;
pub const gfxd_Zraw: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Zraw;
pub const gfxd_Dlflag: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dlflag;
pub const gfxd_Cr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Cr;
pub const gfxd_Num: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Num;
pub const gfxd_Fogz: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Fogz;
pub const gfxd_Fogp: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Fogp;
pub const gfxd_Mtxptr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mtxptr;
pub const gfxd_Gm: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Gm;
pub const gfxd_Mwo_matrix: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mwo_matrix;
pub const gfxd_Linewd: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Linewd;
pub const gfxd_Uctext: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Uctext;
pub const gfxd_Ucdata: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Ucdata;
pub const gfxd_Size: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Size;
pub const gfxd_Lookatptr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Lookatptr;
pub const gfxd_Mtxparam: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mtxparam;
pub const gfxd_Mtxstack: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mtxstack;
pub const gfxd_Mwo_point: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mwo_point;
pub const gfxd_Wscale: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Wscale;
pub const gfxd_Seg: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Seg;
pub const gfxd_Segptr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Segptr;
pub const gfxd_Lightsn: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Lightsn;
pub const gfxd_Numlights: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Numlights;
pub const gfxd_Lightnum: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Lightnum;
pub const gfxd_Lightptr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Lightptr;
pub const gfxd_Tcscale: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Tcscale;
pub const gfxd_Switch: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Switch;
pub const gfxd_St: _bindgen_ty_1 = _bindgen_ty_1::gfxd_St;
pub const gfxd_Stdelta: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Stdelta;
pub const gfxd_Vtxptr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Vtxptr;
pub const gfxd_Vpptr: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Vpptr;
pub const gfxd_Dram: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dram;
pub const gfxd_Sftlo: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Sftlo;
pub const gfxd_Othermodelo: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Othermodelo;
pub const gfxd_Sfthi: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Sfthi;
pub const gfxd_Othermodehi: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Othermodehi;
pub const gfxd_Mw: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mw;
pub const gfxd_Mwo: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mwo;
pub const gfxd_Mwo_clip: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mwo_clip;
pub const gfxd_Mwo_lightcol: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mwo_lightcol;
pub const gfxd_Mv: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mv;
pub const gfxd_Mvo: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Mvo;
pub const gfxd_Dmem: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dmem;
pub const gfxd_Dmaflag: _bindgen_ty_1 = _bindgen_ty_1::gfxd_Dmaflag;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_1 {
    gfxd_Word = 0,
    gfxd_Opcode = 1,
    gfxd_Coordi = 2,
    gfxd_Coordq = 3,
    gfxd_Pal = 4,
    gfxd_Tlut = 5,
    gfxd_Timg = 6,
    gfxd_Tmem = 7,
    gfxd_Tile = 8,
    gfxd_Fmt = 9,
    gfxd_Siz = 10,
    gfxd_Dim = 11,
    gfxd_Cm = 12,
    gfxd_Tm = 13,
    gfxd_Ts = 14,
    gfxd_Dxt = 15,
    gfxd_Tag = 16,
    gfxd_Pm = 17,
    gfxd_Colorpart = 18,
    gfxd_Color = 19,
    gfxd_Lodfrac = 20,
    gfxd_Cimg = 21,
    gfxd_Zimg = 22,
    gfxd_Ac = 23,
    gfxd_Ad = 24,
    gfxd_Cd = 25,
    gfxd_Ccpre = 26,
    gfxd_Ccmuxa = 27,
    gfxd_Ccmuxb = 28,
    gfxd_Ccmuxc = 29,
    gfxd_Ccmuxd = 30,
    gfxd_Acmuxabd = 31,
    gfxd_Acmuxc = 32,
    gfxd_Cv = 33,
    gfxd_Tc = 34,
    gfxd_Cyc = 35,
    gfxd_Zs = 36,
    gfxd_Ck = 37,
    gfxd_Keyscale = 38,
    gfxd_Keywidth = 39,
    gfxd_Zi = 40,
    gfxd_Rm1 = 41,
    gfxd_Rm2 = 42,
    gfxd_Sc = 43,
    gfxd_Td = 44,
    gfxd_Tf = 45,
    gfxd_Tl = 46,
    gfxd_Tt = 47,
    gfxd_Tp = 48,
    gfxd_Line = 49,
    gfxd_Vtx = 50,
    gfxd_Vtxflag = 51,
    gfxd_Dl = 52,
    gfxd_Zraw = 53,
    gfxd_Dlflag = 54,
    gfxd_Cr = 55,
    gfxd_Num = 56,
    gfxd_Fogz = 57,
    gfxd_Fogp = 58,
    gfxd_Mtxptr = 59,
    gfxd_Gm = 60,
    gfxd_Mwo_matrix = 61,
    gfxd_Linewd = 62,
    gfxd_Uctext = 63,
    gfxd_Ucdata = 64,
    gfxd_Size = 65,
    gfxd_Lookatptr = 66,
    gfxd_Mtxparam = 67,
    gfxd_Mtxstack = 68,
    gfxd_Mwo_point = 69,
    gfxd_Wscale = 70,
    gfxd_Seg = 71,
    gfxd_Segptr = 72,
    gfxd_Lightsn = 73,
    gfxd_Numlights = 74,
    gfxd_Lightnum = 75,
    gfxd_Lightptr = 76,
    gfxd_Tcscale = 77,
    gfxd_Switch = 78,
    gfxd_St = 79,
    gfxd_Stdelta = 80,
    gfxd_Vtxptr = 81,
    gfxd_Vpptr = 82,
    gfxd_Dram = 83,
    gfxd_Sftlo = 84,
    gfxd_Othermodelo = 85,
    gfxd_Sfthi = 86,
    gfxd_Othermodehi = 87,
    gfxd_Mw = 88,
    gfxd_Mwo = 89,
    gfxd_Mwo_clip = 90,
    gfxd_Mwo_lightcol = 91,
    gfxd_Mv = 92,
    gfxd_Mvo = 93,
    gfxd_Dmem = 94,
    gfxd_Dmaflag = 95,
}
