/* SPDX-FileCopyrightText: © 2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

//! Argument types

pub const gfxd_Word: ArgType = ArgType::gfxd_Word;
pub const gfxd_Opcode: ArgType = ArgType::gfxd_Opcode;
pub const gfxd_Coordi: ArgType = ArgType::gfxd_Coordi;
pub const gfxd_Coordq: ArgType = ArgType::gfxd_Coordq;
pub const gfxd_Pal: ArgType = ArgType::gfxd_Pal;
pub const gfxd_Tlut: ArgType = ArgType::gfxd_Tlut;
pub const gfxd_Timg: ArgType = ArgType::gfxd_Timg;
pub const gfxd_Tmem: ArgType = ArgType::gfxd_Tmem;
pub const gfxd_Tile: ArgType = ArgType::gfxd_Tile;
pub const gfxd_Fmt: ArgType = ArgType::gfxd_Fmt;
pub const gfxd_Siz: ArgType = ArgType::gfxd_Siz;
pub const gfxd_Dim: ArgType = ArgType::gfxd_Dim;
pub const gfxd_Cm: ArgType = ArgType::gfxd_Cm;
pub const gfxd_Tm: ArgType = ArgType::gfxd_Tm;
pub const gfxd_Ts: ArgType = ArgType::gfxd_Ts;
pub const gfxd_Dxt: ArgType = ArgType::gfxd_Dxt;
pub const gfxd_Tag: ArgType = ArgType::gfxd_Tag;
pub const gfxd_Pm: ArgType = ArgType::gfxd_Pm;
pub const gfxd_Colorpart: ArgType = ArgType::gfxd_Colorpart;
pub const gfxd_Color: ArgType = ArgType::gfxd_Color;
pub const gfxd_Lodfrac: ArgType = ArgType::gfxd_Lodfrac;
pub const gfxd_Cimg: ArgType = ArgType::gfxd_Cimg;
pub const gfxd_Zimg: ArgType = ArgType::gfxd_Zimg;
pub const gfxd_Ac: ArgType = ArgType::gfxd_Ac;
pub const gfxd_Ad: ArgType = ArgType::gfxd_Ad;
pub const gfxd_Cd: ArgType = ArgType::gfxd_Cd;
pub const gfxd_Ccpre: ArgType = ArgType::gfxd_Ccpre;
pub const gfxd_Ccmuxa: ArgType = ArgType::gfxd_Ccmuxa;
pub const gfxd_Ccmuxb: ArgType = ArgType::gfxd_Ccmuxb;
pub const gfxd_Ccmuxc: ArgType = ArgType::gfxd_Ccmuxc;
pub const gfxd_Ccmuxd: ArgType = ArgType::gfxd_Ccmuxd;
pub const gfxd_Acmuxabd: ArgType = ArgType::gfxd_Acmuxabd;
pub const gfxd_Acmuxc: ArgType = ArgType::gfxd_Acmuxc;
pub const gfxd_Cv: ArgType = ArgType::gfxd_Cv;
pub const gfxd_Tc: ArgType = ArgType::gfxd_Tc;
pub const gfxd_Cyc: ArgType = ArgType::gfxd_Cyc;
pub const gfxd_Zs: ArgType = ArgType::gfxd_Zs;
pub const gfxd_Ck: ArgType = ArgType::gfxd_Ck;
pub const gfxd_Keyscale: ArgType = ArgType::gfxd_Keyscale;
pub const gfxd_Keywidth: ArgType = ArgType::gfxd_Keywidth;
pub const gfxd_Zi: ArgType = ArgType::gfxd_Zi;
pub const gfxd_Rm1: ArgType = ArgType::gfxd_Rm1;
pub const gfxd_Rm2: ArgType = ArgType::gfxd_Rm2;
pub const gfxd_Sc: ArgType = ArgType::gfxd_Sc;
pub const gfxd_Td: ArgType = ArgType::gfxd_Td;
pub const gfxd_Tf: ArgType = ArgType::gfxd_Tf;
pub const gfxd_Tl: ArgType = ArgType::gfxd_Tl;
pub const gfxd_Tt: ArgType = ArgType::gfxd_Tt;
pub const gfxd_Tp: ArgType = ArgType::gfxd_Tp;
pub const gfxd_Line: ArgType = ArgType::gfxd_Line;
pub const gfxd_Vtx: ArgType = ArgType::gfxd_Vtx;
pub const gfxd_Vtxflag: ArgType = ArgType::gfxd_Vtxflag;
pub const gfxd_Dl: ArgType = ArgType::gfxd_Dl;
pub const gfxd_Zraw: ArgType = ArgType::gfxd_Zraw;
pub const gfxd_Dlflag: ArgType = ArgType::gfxd_Dlflag;
pub const gfxd_Cr: ArgType = ArgType::gfxd_Cr;
pub const gfxd_Num: ArgType = ArgType::gfxd_Num;
pub const gfxd_Fogz: ArgType = ArgType::gfxd_Fogz;
pub const gfxd_Fogp: ArgType = ArgType::gfxd_Fogp;
pub const gfxd_Mtxptr: ArgType = ArgType::gfxd_Mtxptr;
pub const gfxd_Gm: ArgType = ArgType::gfxd_Gm;
pub const gfxd_Mwo_matrix: ArgType = ArgType::gfxd_Mwo_matrix;
pub const gfxd_Linewd: ArgType = ArgType::gfxd_Linewd;
pub const gfxd_Uctext: ArgType = ArgType::gfxd_Uctext;
pub const gfxd_Ucdata: ArgType = ArgType::gfxd_Ucdata;
pub const gfxd_Size: ArgType = ArgType::gfxd_Size;
pub const gfxd_Lookatptr: ArgType = ArgType::gfxd_Lookatptr;
pub const gfxd_Mtxparam: ArgType = ArgType::gfxd_Mtxparam;
pub const gfxd_Mtxstack: ArgType = ArgType::gfxd_Mtxstack;
pub const gfxd_Mwo_point: ArgType = ArgType::gfxd_Mwo_point;
pub const gfxd_Wscale: ArgType = ArgType::gfxd_Wscale;
pub const gfxd_Seg: ArgType = ArgType::gfxd_Seg;
pub const gfxd_Segptr: ArgType = ArgType::gfxd_Segptr;
pub const gfxd_Lightsn: ArgType = ArgType::gfxd_Lightsn;
pub const gfxd_Numlights: ArgType = ArgType::gfxd_Numlights;
pub const gfxd_Lightnum: ArgType = ArgType::gfxd_Lightnum;
pub const gfxd_Lightptr: ArgType = ArgType::gfxd_Lightptr;
pub const gfxd_Tcscale: ArgType = ArgType::gfxd_Tcscale;
pub const gfxd_Switch: ArgType = ArgType::gfxd_Switch;
pub const gfxd_St: ArgType = ArgType::gfxd_St;
pub const gfxd_Stdelta: ArgType = ArgType::gfxd_Stdelta;
pub const gfxd_Vtxptr: ArgType = ArgType::gfxd_Vtxptr;
pub const gfxd_Vpptr: ArgType = ArgType::gfxd_Vpptr;
pub const gfxd_Dram: ArgType = ArgType::gfxd_Dram;
pub const gfxd_Sftlo: ArgType = ArgType::gfxd_Sftlo;
pub const gfxd_Othermodelo: ArgType = ArgType::gfxd_Othermodelo;
pub const gfxd_Sfthi: ArgType = ArgType::gfxd_Sfthi;
pub const gfxd_Othermodehi: ArgType = ArgType::gfxd_Othermodehi;
pub const gfxd_Mw: ArgType = ArgType::gfxd_Mw;
pub const gfxd_Mwo: ArgType = ArgType::gfxd_Mwo;
pub const gfxd_Mwo_clip: ArgType = ArgType::gfxd_Mwo_clip;
pub const gfxd_Mwo_lightcol: ArgType = ArgType::gfxd_Mwo_lightcol;
pub const gfxd_Mv: ArgType = ArgType::gfxd_Mv;
pub const gfxd_Mvo: ArgType = ArgType::gfxd_Mvo;
pub const gfxd_Dmem: ArgType = ArgType::gfxd_Dmem;
pub const gfxd_Dmaflag: ArgType = ArgType::gfxd_Dmaflag;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ArgType {
    gfxd_Word = 0,
    gfxd_Opcode = 1,
    gfxd_Coordi = 2,
    gfxd_Coordq = 3,
    gfxd_Pal = 4,
    gfxd_Tlut = 5,
    gfxd_Timg = 6,
    gfxd_Tmem = 7,
    gfxd_Tile = 8,
    gfxd_Fmt = 9,
    gfxd_Siz = 10,
    gfxd_Dim = 11,
    gfxd_Cm = 12,
    gfxd_Tm = 13,
    gfxd_Ts = 14,
    gfxd_Dxt = 15,
    gfxd_Tag = 16,
    gfxd_Pm = 17,
    gfxd_Colorpart = 18,
    gfxd_Color = 19,
    gfxd_Lodfrac = 20,
    gfxd_Cimg = 21,
    gfxd_Zimg = 22,
    gfxd_Ac = 23,
    gfxd_Ad = 24,
    gfxd_Cd = 25,
    gfxd_Ccpre = 26,
    gfxd_Ccmuxa = 27,
    gfxd_Ccmuxb = 28,
    gfxd_Ccmuxc = 29,
    gfxd_Ccmuxd = 30,
    gfxd_Acmuxabd = 31,
    gfxd_Acmuxc = 32,
    gfxd_Cv = 33,
    gfxd_Tc = 34,
    gfxd_Cyc = 35,
    gfxd_Zs = 36,
    gfxd_Ck = 37,
    gfxd_Keyscale = 38,
    gfxd_Keywidth = 39,
    gfxd_Zi = 40,
    gfxd_Rm1 = 41,
    gfxd_Rm2 = 42,
    gfxd_Sc = 43,
    gfxd_Td = 44,
    gfxd_Tf = 45,
    gfxd_Tl = 46,
    gfxd_Tt = 47,
    gfxd_Tp = 48,
    gfxd_Line = 49,
    gfxd_Vtx = 50,
    gfxd_Vtxflag = 51,
    gfxd_Dl = 52,
    gfxd_Zraw = 53,
    gfxd_Dlflag = 54,
    gfxd_Cr = 55,
    gfxd_Num = 56,
    gfxd_Fogz = 57,
    gfxd_Fogp = 58,
    gfxd_Mtxptr = 59,
    gfxd_Gm = 60,
    gfxd_Mwo_matrix = 61,
    gfxd_Linewd = 62,
    gfxd_Uctext = 63,
    gfxd_Ucdata = 64,
    gfxd_Size = 65,
    gfxd_Lookatptr = 66,
    gfxd_Mtxparam = 67,
    gfxd_Mtxstack = 68,
    gfxd_Mwo_point = 69,
    gfxd_Wscale = 70,
    gfxd_Seg = 71,
    gfxd_Segptr = 72,
    gfxd_Lightsn = 73,
    gfxd_Numlights = 74,
    gfxd_Lightnum = 75,
    gfxd_Lightptr = 76,
    gfxd_Tcscale = 77,
    gfxd_Switch = 78,
    gfxd_St = 79,
    gfxd_Stdelta = 80,
    gfxd_Vtxptr = 81,
    gfxd_Vpptr = 82,
    gfxd_Dram = 83,
    gfxd_Sftlo = 84,
    gfxd_Othermodelo = 85,
    gfxd_Sfthi = 86,
    gfxd_Othermodehi = 87,
    gfxd_Mw = 88,
    gfxd_Mwo = 89,
    gfxd_Mwo_clip = 90,
    gfxd_Mwo_lightcol = 91,
    gfxd_Mv = 92,
    gfxd_Mvo = 93,
    gfxd_Dmem = 94,
    gfxd_Dmaflag = 95,
}
