/* SPDX-FileCopyrightText: © 2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

//! Macro ids

pub const gfxd_Invalid: MacroId = MacroId::gfxd_Invalid;
pub const gfxd_DPFillRectangle: MacroId = MacroId::gfxd_DPFillRectangle;
pub const gfxd_DPFullSync: MacroId = MacroId::gfxd_DPFullSync;
pub const gfxd_DPLoadSync: MacroId = MacroId::gfxd_DPLoadSync;
pub const gfxd_DPTileSync: MacroId = MacroId::gfxd_DPTileSync;
pub const gfxd_DPPipeSync: MacroId = MacroId::gfxd_DPPipeSync;
pub const gfxd_DPLoadTLUT_pal16: MacroId = MacroId::gfxd_DPLoadTLUT_pal16;
pub const gfxd_DPLoadTLUT_pal256: MacroId = MacroId::gfxd_DPLoadTLUT_pal256;
pub const gfxd_DPLoadMultiBlockYuvS: MacroId = MacroId::gfxd_DPLoadMultiBlockYuvS;
pub const gfxd_DPLoadMultiBlockYuv: MacroId = MacroId::gfxd_DPLoadMultiBlockYuv;
pub const gfxd_DPLoadMultiBlock_4bS: MacroId = MacroId::gfxd_DPLoadMultiBlock_4bS;
pub const gfxd_DPLoadMultiBlock_4b: MacroId = MacroId::gfxd_DPLoadMultiBlock_4b;
pub const gfxd_DPLoadMultiBlockS: MacroId = MacroId::gfxd_DPLoadMultiBlockS;
pub const gfxd_DPLoadMultiBlock: MacroId = MacroId::gfxd_DPLoadMultiBlock;
pub const gfxd__DPLoadTextureBlockYuvS: MacroId = MacroId::gfxd__DPLoadTextureBlockYuvS;
pub const gfxd__DPLoadTextureBlockYuv: MacroId = MacroId::gfxd__DPLoadTextureBlockYuv;
pub const gfxd__DPLoadTextureBlock_4bS: MacroId = MacroId::gfxd__DPLoadTextureBlock_4bS;
pub const gfxd__DPLoadTextureBlock_4b: MacroId = MacroId::gfxd__DPLoadTextureBlock_4b;
pub const gfxd__DPLoadTextureBlockS: MacroId = MacroId::gfxd__DPLoadTextureBlockS;
pub const gfxd__DPLoadTextureBlock: MacroId = MacroId::gfxd__DPLoadTextureBlock;
pub const gfxd_DPLoadTextureBlockYuvS: MacroId = MacroId::gfxd_DPLoadTextureBlockYuvS;
pub const gfxd_DPLoadTextureBlockYuv: MacroId = MacroId::gfxd_DPLoadTextureBlockYuv;
pub const gfxd_DPLoadTextureBlock_4bS: MacroId = MacroId::gfxd_DPLoadTextureBlock_4bS;
pub const gfxd_DPLoadTextureBlock_4b: MacroId = MacroId::gfxd_DPLoadTextureBlock_4b;
pub const gfxd_DPLoadTextureBlockS: MacroId = MacroId::gfxd_DPLoadTextureBlockS;
pub const gfxd_DPLoadTextureBlock: MacroId = MacroId::gfxd_DPLoadTextureBlock;
pub const gfxd_DPLoadMultiTileYuv: MacroId = MacroId::gfxd_DPLoadMultiTileYuv;
pub const gfxd_DPLoadMultiTile_4b: MacroId = MacroId::gfxd_DPLoadMultiTile_4b;
pub const gfxd_DPLoadMultiTile: MacroId = MacroId::gfxd_DPLoadMultiTile;
pub const gfxd__DPLoadTextureTileYuv: MacroId = MacroId::gfxd__DPLoadTextureTileYuv;
pub const gfxd__DPLoadTextureTile_4b: MacroId = MacroId::gfxd__DPLoadTextureTile_4b;
pub const gfxd__DPLoadTextureTile: MacroId = MacroId::gfxd__DPLoadTextureTile;
pub const gfxd_DPLoadTextureTileYuv: MacroId = MacroId::gfxd_DPLoadTextureTileYuv;
pub const gfxd_DPLoadTextureTile_4b: MacroId = MacroId::gfxd_DPLoadTextureTile_4b;
pub const gfxd_DPLoadTextureTile: MacroId = MacroId::gfxd_DPLoadTextureTile;
pub const gfxd_DPLoadBlock: MacroId = MacroId::gfxd_DPLoadBlock;
pub const gfxd_DPNoOp: MacroId = MacroId::gfxd_DPNoOp;
pub const gfxd_DPNoOpTag: MacroId = MacroId::gfxd_DPNoOpTag;
pub const gfxd_DPPipelineMode: MacroId = MacroId::gfxd_DPPipelineMode;
pub const gfxd_DPSetBlendColor: MacroId = MacroId::gfxd_DPSetBlendColor;
pub const gfxd_DPSetEnvColor: MacroId = MacroId::gfxd_DPSetEnvColor;
pub const gfxd_DPSetFillColor: MacroId = MacroId::gfxd_DPSetFillColor;
pub const gfxd_DPSetFogColor: MacroId = MacroId::gfxd_DPSetFogColor;
pub const gfxd_DPSetPrimColor: MacroId = MacroId::gfxd_DPSetPrimColor;
pub const gfxd_DPSetColorImage: MacroId = MacroId::gfxd_DPSetColorImage;
pub const gfxd_DPSetDepthImage: MacroId = MacroId::gfxd_DPSetDepthImage;
pub const gfxd_DPSetTextureImage: MacroId = MacroId::gfxd_DPSetTextureImage;
pub const gfxd_DPSetAlphaCompare: MacroId = MacroId::gfxd_DPSetAlphaCompare;
pub const gfxd_DPSetAlphaDither: MacroId = MacroId::gfxd_DPSetAlphaDither;
pub const gfxd_DPSetColorDither: MacroId = MacroId::gfxd_DPSetColorDither;
pub const gfxd_DPSetCombineMode: MacroId = MacroId::gfxd_DPSetCombineMode;
pub const gfxd_DPSetCombineLERP: MacroId = MacroId::gfxd_DPSetCombineLERP;
pub const gfxd_DPSetConvert: MacroId = MacroId::gfxd_DPSetConvert;
pub const gfxd_DPSetTextureConvert: MacroId = MacroId::gfxd_DPSetTextureConvert;
pub const gfxd_DPSetCycleType: MacroId = MacroId::gfxd_DPSetCycleType;
pub const gfxd_DPSetDepthSource: MacroId = MacroId::gfxd_DPSetDepthSource;
pub const gfxd_DPSetCombineKey: MacroId = MacroId::gfxd_DPSetCombineKey;
pub const gfxd_DPSetKeyGB: MacroId = MacroId::gfxd_DPSetKeyGB;
pub const gfxd_DPSetKeyR: MacroId = MacroId::gfxd_DPSetKeyR;
pub const gfxd_DPSetPrimDepth: MacroId = MacroId::gfxd_DPSetPrimDepth;
pub const gfxd_DPSetRenderMode: MacroId = MacroId::gfxd_DPSetRenderMode;
pub const gfxd_DPSetScissor: MacroId = MacroId::gfxd_DPSetScissor;
pub const gfxd_DPSetScissorFrac: MacroId = MacroId::gfxd_DPSetScissorFrac;
pub const gfxd_DPSetTextureDetail: MacroId = MacroId::gfxd_DPSetTextureDetail;
pub const gfxd_DPSetTextureFilter: MacroId = MacroId::gfxd_DPSetTextureFilter;
pub const gfxd_DPSetTextureLOD: MacroId = MacroId::gfxd_DPSetTextureLOD;
pub const gfxd_DPSetTextureLUT: MacroId = MacroId::gfxd_DPSetTextureLUT;
pub const gfxd_DPSetTexturePersp: MacroId = MacroId::gfxd_DPSetTexturePersp;
pub const gfxd_DPSetTile: MacroId = MacroId::gfxd_DPSetTile;
pub const gfxd_DPSetTileSize: MacroId = MacroId::gfxd_DPSetTileSize;
pub const gfxd_SP1Triangle: MacroId = MacroId::gfxd_SP1Triangle;
pub const gfxd_SP2Triangles: MacroId = MacroId::gfxd_SP2Triangles;
pub const gfxd_SP1Quadrangle: MacroId = MacroId::gfxd_SP1Quadrangle;
pub const gfxd_SPBranchLessZraw: MacroId = MacroId::gfxd_SPBranchLessZraw;
pub const gfxd_SPBranchList: MacroId = MacroId::gfxd_SPBranchList;
pub const gfxd_SPClipRatio: MacroId = MacroId::gfxd_SPClipRatio;
pub const gfxd_SPCullDisplayList: MacroId = MacroId::gfxd_SPCullDisplayList;
pub const gfxd_SPDisplayList: MacroId = MacroId::gfxd_SPDisplayList;
pub const gfxd_SPEndDisplayList: MacroId = MacroId::gfxd_SPEndDisplayList;
pub const gfxd_SPFogFactor: MacroId = MacroId::gfxd_SPFogFactor;
pub const gfxd_SPFogPosition: MacroId = MacroId::gfxd_SPFogPosition;
pub const gfxd_SPForceMatrix: MacroId = MacroId::gfxd_SPForceMatrix;
pub const gfxd_SPSetGeometryMode: MacroId = MacroId::gfxd_SPSetGeometryMode;
pub const gfxd_SPClearGeometryMode: MacroId = MacroId::gfxd_SPClearGeometryMode;
pub const gfxd_SPLoadGeometryMode: MacroId = MacroId::gfxd_SPLoadGeometryMode;
pub const gfxd_SPInsertMatrix: MacroId = MacroId::gfxd_SPInsertMatrix;
pub const gfxd_SPLine3D: MacroId = MacroId::gfxd_SPLine3D;
pub const gfxd_SPLineW3D: MacroId = MacroId::gfxd_SPLineW3D;
pub const gfxd_SPLoadUcode: MacroId = MacroId::gfxd_SPLoadUcode;
pub const gfxd_SPLookAtX: MacroId = MacroId::gfxd_SPLookAtX;
pub const gfxd_SPLookAtY: MacroId = MacroId::gfxd_SPLookAtY;
pub const gfxd_SPLookAt: MacroId = MacroId::gfxd_SPLookAt;
pub const gfxd_SPMatrix: MacroId = MacroId::gfxd_SPMatrix;
pub const gfxd_SPModifyVertex: MacroId = MacroId::gfxd_SPModifyVertex;
pub const gfxd_SPPerspNormalize: MacroId = MacroId::gfxd_SPPerspNormalize;
pub const gfxd_SPPopMatrix: MacroId = MacroId::gfxd_SPPopMatrix;
pub const gfxd_SPPopMatrixN: MacroId = MacroId::gfxd_SPPopMatrixN;
pub const gfxd_SPSegment: MacroId = MacroId::gfxd_SPSegment;
pub const gfxd_SPSetLights1: MacroId = MacroId::gfxd_SPSetLights1;
pub const gfxd_SPSetLights2: MacroId = MacroId::gfxd_SPSetLights2;
pub const gfxd_SPSetLights3: MacroId = MacroId::gfxd_SPSetLights3;
pub const gfxd_SPSetLights4: MacroId = MacroId::gfxd_SPSetLights4;
pub const gfxd_SPSetLights5: MacroId = MacroId::gfxd_SPSetLights5;
pub const gfxd_SPSetLights6: MacroId = MacroId::gfxd_SPSetLights6;
pub const gfxd_SPSetLights7: MacroId = MacroId::gfxd_SPSetLights7;
pub const gfxd_SPNumLights: MacroId = MacroId::gfxd_SPNumLights;
pub const gfxd_SPLight: MacroId = MacroId::gfxd_SPLight;
pub const gfxd_SPLightColor: MacroId = MacroId::gfxd_SPLightColor;
pub const gfxd_SPTexture: MacroId = MacroId::gfxd_SPTexture;
pub const gfxd_SPTextureRectangle: MacroId = MacroId::gfxd_SPTextureRectangle;
pub const gfxd_SPTextureRectangleFlip: MacroId = MacroId::gfxd_SPTextureRectangleFlip;
pub const gfxd_SPVertex: MacroId = MacroId::gfxd_SPVertex;
pub const gfxd_SPViewport: MacroId = MacroId::gfxd_SPViewport;
pub const gfxd_DPLoadTLUTCmd: MacroId = MacroId::gfxd_DPLoadTLUTCmd;
pub const gfxd_DPLoadTLUT: MacroId = MacroId::gfxd_DPLoadTLUT;
pub const gfxd_BranchZ: MacroId = MacroId::gfxd_BranchZ;
pub const gfxd_DisplayList: MacroId = MacroId::gfxd_DisplayList;
pub const gfxd_DPHalf1: MacroId = MacroId::gfxd_DPHalf1;
pub const gfxd_DPHalf2: MacroId = MacroId::gfxd_DPHalf2;
pub const gfxd_DPWord: MacroId = MacroId::gfxd_DPWord;
pub const gfxd_DPLoadTile: MacroId = MacroId::gfxd_DPLoadTile;
pub const gfxd_SPGeometryMode: MacroId = MacroId::gfxd_SPGeometryMode;
pub const gfxd_SPSetOtherMode: MacroId = MacroId::gfxd_SPSetOtherMode;
pub const gfxd_SPSetOtherModeLo: MacroId = MacroId::gfxd_SPSetOtherModeLo;
pub const gfxd_SPSetOtherModeHi: MacroId = MacroId::gfxd_SPSetOtherModeHi;
pub const gfxd_DPSetOtherMode: MacroId = MacroId::gfxd_DPSetOtherMode;
pub const gfxd_MoveWd: MacroId = MacroId::gfxd_MoveWd;
pub const gfxd_MoveMem: MacroId = MacroId::gfxd_MoveMem;
pub const gfxd_SPDma_io: MacroId = MacroId::gfxd_SPDma_io;
pub const gfxd_SPDmaRead: MacroId = MacroId::gfxd_SPDmaRead;
pub const gfxd_SPDmaWrite: MacroId = MacroId::gfxd_SPDmaWrite;
pub const gfxd_LoadUcode: MacroId = MacroId::gfxd_LoadUcode;
pub const gfxd_SPLoadUcodeEx: MacroId = MacroId::gfxd_SPLoadUcodeEx;
pub const gfxd_TexRect: MacroId = MacroId::gfxd_TexRect;
pub const gfxd_TexRectFlip: MacroId = MacroId::gfxd_TexRectFlip;
pub const gfxd_SPNoOp: MacroId = MacroId::gfxd_SPNoOp;
pub const gfxd_Special3: MacroId = MacroId::gfxd_Special3;
pub const gfxd_Special2: MacroId = MacroId::gfxd_Special2;
pub const gfxd_Special1: MacroId = MacroId::gfxd_Special1;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MacroId {
    gfxd_Invalid = 0,
    gfxd_DPFillRectangle = 1,
    gfxd_DPFullSync = 2,
    gfxd_DPLoadSync = 3,
    gfxd_DPTileSync = 4,
    gfxd_DPPipeSync = 5,
    gfxd_DPLoadTLUT_pal16 = 6,
    gfxd_DPLoadTLUT_pal256 = 7,
    gfxd_DPLoadMultiBlockYuvS = 8,
    gfxd_DPLoadMultiBlockYuv = 9,
    gfxd_DPLoadMultiBlock_4bS = 10,
    gfxd_DPLoadMultiBlock_4b = 11,
    gfxd_DPLoadMultiBlockS = 12,
    gfxd_DPLoadMultiBlock = 13,
    gfxd__DPLoadTextureBlockYuvS = 14,
    gfxd__DPLoadTextureBlockYuv = 15,
    gfxd__DPLoadTextureBlock_4bS = 16,
    gfxd__DPLoadTextureBlock_4b = 17,
    gfxd__DPLoadTextureBlockS = 18,
    gfxd__DPLoadTextureBlock = 19,
    gfxd_DPLoadTextureBlockYuvS = 20,
    gfxd_DPLoadTextureBlockYuv = 21,
    gfxd_DPLoadTextureBlock_4bS = 22,
    gfxd_DPLoadTextureBlock_4b = 23,
    gfxd_DPLoadTextureBlockS = 24,
    gfxd_DPLoadTextureBlock = 25,
    gfxd_DPLoadMultiTileYuv = 26,
    gfxd_DPLoadMultiTile_4b = 27,
    gfxd_DPLoadMultiTile = 28,
    gfxd__DPLoadTextureTileYuv = 29,
    gfxd__DPLoadTextureTile_4b = 30,
    gfxd__DPLoadTextureTile = 31,
    gfxd_DPLoadTextureTileYuv = 32,
    gfxd_DPLoadTextureTile_4b = 33,
    gfxd_DPLoadTextureTile = 34,
    gfxd_DPLoadBlock = 35,
    gfxd_DPNoOp = 36,
    gfxd_DPNoOpTag = 37,
    gfxd_DPPipelineMode = 38,
    gfxd_DPSetBlendColor = 39,
    gfxd_DPSetEnvColor = 40,
    gfxd_DPSetFillColor = 41,
    gfxd_DPSetFogColor = 42,
    gfxd_DPSetPrimColor = 43,
    gfxd_DPSetColorImage = 44,
    gfxd_DPSetDepthImage = 45,
    gfxd_DPSetTextureImage = 46,
    gfxd_DPSetAlphaCompare = 47,
    gfxd_DPSetAlphaDither = 48,
    gfxd_DPSetColorDither = 49,
    gfxd_DPSetCombineMode = 50,
    gfxd_DPSetCombineLERP = 51,
    gfxd_DPSetConvert = 52,
    gfxd_DPSetTextureConvert = 53,
    gfxd_DPSetCycleType = 54,
    gfxd_DPSetDepthSource = 55,
    gfxd_DPSetCombineKey = 56,
    gfxd_DPSetKeyGB = 57,
    gfxd_DPSetKeyR = 58,
    gfxd_DPSetPrimDepth = 59,
    gfxd_DPSetRenderMode = 60,
    gfxd_DPSetScissor = 61,
    gfxd_DPSetScissorFrac = 62,
    gfxd_DPSetTextureDetail = 63,
    gfxd_DPSetTextureFilter = 64,
    gfxd_DPSetTextureLOD = 65,
    gfxd_DPSetTextureLUT = 66,
    gfxd_DPSetTexturePersp = 67,
    gfxd_DPSetTile = 68,
    gfxd_DPSetTileSize = 69,
    gfxd_SP1Triangle = 70,
    gfxd_SP2Triangles = 71,
    gfxd_SP1Quadrangle = 72,
    gfxd_SPBranchLessZraw = 73,
    gfxd_SPBranchList = 74,
    gfxd_SPClipRatio = 75,
    gfxd_SPCullDisplayList = 76,
    gfxd_SPDisplayList = 77,
    gfxd_SPEndDisplayList = 78,
    gfxd_SPFogFactor = 79,
    gfxd_SPFogPosition = 80,
    gfxd_SPForceMatrix = 81,
    gfxd_SPSetGeometryMode = 82,
    gfxd_SPClearGeometryMode = 83,
    gfxd_SPLoadGeometryMode = 84,
    gfxd_SPInsertMatrix = 85,
    gfxd_SPLine3D = 86,
    gfxd_SPLineW3D = 87,
    gfxd_SPLoadUcode = 88,
    gfxd_SPLookAtX = 89,
    gfxd_SPLookAtY = 90,
    gfxd_SPLookAt = 91,
    gfxd_SPMatrix = 92,
    gfxd_SPModifyVertex = 93,
    gfxd_SPPerspNormalize = 94,
    gfxd_SPPopMatrix = 95,
    gfxd_SPPopMatrixN = 96,
    gfxd_SPSegment = 97,
    gfxd_SPSetLights1 = 98,
    gfxd_SPSetLights2 = 99,
    gfxd_SPSetLights3 = 100,
    gfxd_SPSetLights4 = 101,
    gfxd_SPSetLights5 = 102,
    gfxd_SPSetLights6 = 103,
    gfxd_SPSetLights7 = 104,
    gfxd_SPNumLights = 105,
    gfxd_SPLight = 106,
    gfxd_SPLightColor = 107,
    gfxd_SPTexture = 108,
    gfxd_SPTextureRectangle = 109,
    gfxd_SPTextureRectangleFlip = 110,
    gfxd_SPVertex = 111,
    gfxd_SPViewport = 112,
    gfxd_DPLoadTLUTCmd = 113,
    gfxd_DPLoadTLUT = 114,
    gfxd_BranchZ = 115,
    gfxd_DisplayList = 116,
    gfxd_DPHalf1 = 117,
    gfxd_DPHalf2 = 118,
    gfxd_DPWord = 119,
    gfxd_DPLoadTile = 120,
    gfxd_SPGeometryMode = 121,
    gfxd_SPSetOtherMode = 122,
    gfxd_SPSetOtherModeLo = 123,
    gfxd_SPSetOtherModeHi = 124,
    gfxd_DPSetOtherMode = 125,
    gfxd_MoveWd = 126,
    gfxd_MoveMem = 127,
    gfxd_SPDma_io = 128,
    gfxd_SPDmaRead = 129,
    gfxd_SPDmaWrite = 130,
    gfxd_LoadUcode = 131,
    gfxd_SPLoadUcodeEx = 132,
    gfxd_TexRect = 133,
    gfxd_TexRectFlip = 134,
    gfxd_SPNoOp = 135,
    gfxd_Special3 = 136,
    gfxd_Special2 = 137,
    gfxd_Special1 = 138,
}
