/* SPDX-FileCopyrightText: © 2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

//! Macro ids

pub const gfxd_Invalid: _bindgen_ty_2 = _bindgen_ty_2::gfxd_Invalid;
pub const gfxd_DPFillRectangle: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPFillRectangle;
pub const gfxd_DPFullSync: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPFullSync;
pub const gfxd_DPLoadSync: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadSync;
pub const gfxd_DPTileSync: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPTileSync;
pub const gfxd_DPPipeSync: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPPipeSync;
pub const gfxd_DPLoadTLUT_pal16: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTLUT_pal16;
pub const gfxd_DPLoadTLUT_pal256: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTLUT_pal256;
pub const gfxd_DPLoadMultiBlockYuvS: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiBlockYuvS;
pub const gfxd_DPLoadMultiBlockYuv: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiBlockYuv;
pub const gfxd_DPLoadMultiBlock_4bS: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiBlock_4bS;
pub const gfxd_DPLoadMultiBlock_4b: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiBlock_4b;
pub const gfxd_DPLoadMultiBlockS: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiBlockS;
pub const gfxd_DPLoadMultiBlock: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiBlock;
pub const gfxd__DPLoadTextureBlockYuvS: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureBlockYuvS;
pub const gfxd__DPLoadTextureBlockYuv: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureBlockYuv;
pub const gfxd__DPLoadTextureBlock_4bS: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureBlock_4bS;
pub const gfxd__DPLoadTextureBlock_4b: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureBlock_4b;
pub const gfxd__DPLoadTextureBlockS: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureBlockS;
pub const gfxd__DPLoadTextureBlock: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureBlock;
pub const gfxd_DPLoadTextureBlockYuvS: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureBlockYuvS;
pub const gfxd_DPLoadTextureBlockYuv: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureBlockYuv;
pub const gfxd_DPLoadTextureBlock_4bS: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureBlock_4bS;
pub const gfxd_DPLoadTextureBlock_4b: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureBlock_4b;
pub const gfxd_DPLoadTextureBlockS: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureBlockS;
pub const gfxd_DPLoadTextureBlock: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureBlock;
pub const gfxd_DPLoadMultiTileYuv: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiTileYuv;
pub const gfxd_DPLoadMultiTile_4b: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiTile_4b;
pub const gfxd_DPLoadMultiTile: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadMultiTile;
pub const gfxd__DPLoadTextureTileYuv: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureTileYuv;
pub const gfxd__DPLoadTextureTile_4b: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureTile_4b;
pub const gfxd__DPLoadTextureTile: _bindgen_ty_2 = _bindgen_ty_2::gfxd__DPLoadTextureTile;
pub const gfxd_DPLoadTextureTileYuv: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureTileYuv;
pub const gfxd_DPLoadTextureTile_4b: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureTile_4b;
pub const gfxd_DPLoadTextureTile: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTextureTile;
pub const gfxd_DPLoadBlock: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadBlock;
pub const gfxd_DPNoOp: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPNoOp;
pub const gfxd_DPNoOpTag: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPNoOpTag;
pub const gfxd_DPPipelineMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPPipelineMode;
pub const gfxd_DPSetBlendColor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetBlendColor;
pub const gfxd_DPSetEnvColor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetEnvColor;
pub const gfxd_DPSetFillColor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetFillColor;
pub const gfxd_DPSetFogColor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetFogColor;
pub const gfxd_DPSetPrimColor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetPrimColor;
pub const gfxd_DPSetColorImage: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetColorImage;
pub const gfxd_DPSetDepthImage: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetDepthImage;
pub const gfxd_DPSetTextureImage: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTextureImage;
pub const gfxd_DPSetAlphaCompare: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetAlphaCompare;
pub const gfxd_DPSetAlphaDither: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetAlphaDither;
pub const gfxd_DPSetColorDither: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetColorDither;
pub const gfxd_DPSetCombineMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetCombineMode;
pub const gfxd_DPSetCombineLERP: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetCombineLERP;
pub const gfxd_DPSetConvert: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetConvert;
pub const gfxd_DPSetTextureConvert: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTextureConvert;
pub const gfxd_DPSetCycleType: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetCycleType;
pub const gfxd_DPSetDepthSource: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetDepthSource;
pub const gfxd_DPSetCombineKey: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetCombineKey;
pub const gfxd_DPSetKeyGB: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetKeyGB;
pub const gfxd_DPSetKeyR: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetKeyR;
pub const gfxd_DPSetPrimDepth: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetPrimDepth;
pub const gfxd_DPSetRenderMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetRenderMode;
pub const gfxd_DPSetScissor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetScissor;
pub const gfxd_DPSetScissorFrac: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetScissorFrac;
pub const gfxd_DPSetTextureDetail: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTextureDetail;
pub const gfxd_DPSetTextureFilter: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTextureFilter;
pub const gfxd_DPSetTextureLOD: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTextureLOD;
pub const gfxd_DPSetTextureLUT: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTextureLUT;
pub const gfxd_DPSetTexturePersp: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTexturePersp;
pub const gfxd_DPSetTile: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTile;
pub const gfxd_DPSetTileSize: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetTileSize;
pub const gfxd_SP1Triangle: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SP1Triangle;
pub const gfxd_SP2Triangles: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SP2Triangles;
pub const gfxd_SP1Quadrangle: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SP1Quadrangle;
pub const gfxd_SPBranchLessZraw: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPBranchLessZraw;
pub const gfxd_SPBranchList: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPBranchList;
pub const gfxd_SPClipRatio: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPClipRatio;
pub const gfxd_SPCullDisplayList: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPCullDisplayList;
pub const gfxd_SPDisplayList: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPDisplayList;
pub const gfxd_SPEndDisplayList: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPEndDisplayList;
pub const gfxd_SPFogFactor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPFogFactor;
pub const gfxd_SPFogPosition: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPFogPosition;
pub const gfxd_SPForceMatrix: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPForceMatrix;
pub const gfxd_SPSetGeometryMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetGeometryMode;
pub const gfxd_SPClearGeometryMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPClearGeometryMode;
pub const gfxd_SPLoadGeometryMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLoadGeometryMode;
pub const gfxd_SPInsertMatrix: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPInsertMatrix;
pub const gfxd_SPLine3D: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLine3D;
pub const gfxd_SPLineW3D: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLineW3D;
pub const gfxd_SPLoadUcode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLoadUcode;
pub const gfxd_SPLookAtX: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLookAtX;
pub const gfxd_SPLookAtY: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLookAtY;
pub const gfxd_SPLookAt: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLookAt;
pub const gfxd_SPMatrix: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPMatrix;
pub const gfxd_SPModifyVertex: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPModifyVertex;
pub const gfxd_SPPerspNormalize: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPPerspNormalize;
pub const gfxd_SPPopMatrix: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPPopMatrix;
pub const gfxd_SPPopMatrixN: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPPopMatrixN;
pub const gfxd_SPSegment: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSegment;
pub const gfxd_SPSetLights1: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights1;
pub const gfxd_SPSetLights2: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights2;
pub const gfxd_SPSetLights3: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights3;
pub const gfxd_SPSetLights4: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights4;
pub const gfxd_SPSetLights5: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights5;
pub const gfxd_SPSetLights6: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights6;
pub const gfxd_SPSetLights7: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetLights7;
pub const gfxd_SPNumLights: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPNumLights;
pub const gfxd_SPLight: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLight;
pub const gfxd_SPLightColor: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLightColor;
pub const gfxd_SPTexture: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPTexture;
pub const gfxd_SPTextureRectangle: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPTextureRectangle;
pub const gfxd_SPTextureRectangleFlip: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPTextureRectangleFlip;
pub const gfxd_SPVertex: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPVertex;
pub const gfxd_SPViewport: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPViewport;
pub const gfxd_DPLoadTLUTCmd: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTLUTCmd;
pub const gfxd_DPLoadTLUT: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTLUT;
pub const gfxd_BranchZ: _bindgen_ty_2 = _bindgen_ty_2::gfxd_BranchZ;
pub const gfxd_DisplayList: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DisplayList;
pub const gfxd_DPHalf1: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPHalf1;
pub const gfxd_DPHalf2: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPHalf2;
pub const gfxd_DPWord: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPWord;
pub const gfxd_DPLoadTile: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPLoadTile;
pub const gfxd_SPGeometryMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPGeometryMode;
pub const gfxd_SPSetOtherMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetOtherMode;
pub const gfxd_SPSetOtherModeLo: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetOtherModeLo;
pub const gfxd_SPSetOtherModeHi: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPSetOtherModeHi;
pub const gfxd_DPSetOtherMode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_DPSetOtherMode;
pub const gfxd_MoveWd: _bindgen_ty_2 = _bindgen_ty_2::gfxd_MoveWd;
pub const gfxd_MoveMem: _bindgen_ty_2 = _bindgen_ty_2::gfxd_MoveMem;
pub const gfxd_SPDma_io: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPDma_io;
pub const gfxd_SPDmaRead: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPDmaRead;
pub const gfxd_SPDmaWrite: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPDmaWrite;
pub const gfxd_LoadUcode: _bindgen_ty_2 = _bindgen_ty_2::gfxd_LoadUcode;
pub const gfxd_SPLoadUcodeEx: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPLoadUcodeEx;
pub const gfxd_TexRect: _bindgen_ty_2 = _bindgen_ty_2::gfxd_TexRect;
pub const gfxd_TexRectFlip: _bindgen_ty_2 = _bindgen_ty_2::gfxd_TexRectFlip;
pub const gfxd_SPNoOp: _bindgen_ty_2 = _bindgen_ty_2::gfxd_SPNoOp;
pub const gfxd_Special3: _bindgen_ty_2 = _bindgen_ty_2::gfxd_Special3;
pub const gfxd_Special2: _bindgen_ty_2 = _bindgen_ty_2::gfxd_Special2;
pub const gfxd_Special1: _bindgen_ty_2 = _bindgen_ty_2::gfxd_Special1;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_2 {
    gfxd_Invalid = 0,
    gfxd_DPFillRectangle = 1,
    gfxd_DPFullSync = 2,
    gfxd_DPLoadSync = 3,
    gfxd_DPTileSync = 4,
    gfxd_DPPipeSync = 5,
    gfxd_DPLoadTLUT_pal16 = 6,
    gfxd_DPLoadTLUT_pal256 = 7,
    gfxd_DPLoadMultiBlockYuvS = 8,
    gfxd_DPLoadMultiBlockYuv = 9,
    gfxd_DPLoadMultiBlock_4bS = 10,
    gfxd_DPLoadMultiBlock_4b = 11,
    gfxd_DPLoadMultiBlockS = 12,
    gfxd_DPLoadMultiBlock = 13,
    gfxd__DPLoadTextureBlockYuvS = 14,
    gfxd__DPLoadTextureBlockYuv = 15,
    gfxd__DPLoadTextureBlock_4bS = 16,
    gfxd__DPLoadTextureBlock_4b = 17,
    gfxd__DPLoadTextureBlockS = 18,
    gfxd__DPLoadTextureBlock = 19,
    gfxd_DPLoadTextureBlockYuvS = 20,
    gfxd_DPLoadTextureBlockYuv = 21,
    gfxd_DPLoadTextureBlock_4bS = 22,
    gfxd_DPLoadTextureBlock_4b = 23,
    gfxd_DPLoadTextureBlockS = 24,
    gfxd_DPLoadTextureBlock = 25,
    gfxd_DPLoadMultiTileYuv = 26,
    gfxd_DPLoadMultiTile_4b = 27,
    gfxd_DPLoadMultiTile = 28,
    gfxd__DPLoadTextureTileYuv = 29,
    gfxd__DPLoadTextureTile_4b = 30,
    gfxd__DPLoadTextureTile = 31,
    gfxd_DPLoadTextureTileYuv = 32,
    gfxd_DPLoadTextureTile_4b = 33,
    gfxd_DPLoadTextureTile = 34,
    gfxd_DPLoadBlock = 35,
    gfxd_DPNoOp = 36,
    gfxd_DPNoOpTag = 37,
    gfxd_DPPipelineMode = 38,
    gfxd_DPSetBlendColor = 39,
    gfxd_DPSetEnvColor = 40,
    gfxd_DPSetFillColor = 41,
    gfxd_DPSetFogColor = 42,
    gfxd_DPSetPrimColor = 43,
    gfxd_DPSetColorImage = 44,
    gfxd_DPSetDepthImage = 45,
    gfxd_DPSetTextureImage = 46,
    gfxd_DPSetAlphaCompare = 47,
    gfxd_DPSetAlphaDither = 48,
    gfxd_DPSetColorDither = 49,
    gfxd_DPSetCombineMode = 50,
    gfxd_DPSetCombineLERP = 51,
    gfxd_DPSetConvert = 52,
    gfxd_DPSetTextureConvert = 53,
    gfxd_DPSetCycleType = 54,
    gfxd_DPSetDepthSource = 55,
    gfxd_DPSetCombineKey = 56,
    gfxd_DPSetKeyGB = 57,
    gfxd_DPSetKeyR = 58,
    gfxd_DPSetPrimDepth = 59,
    gfxd_DPSetRenderMode = 60,
    gfxd_DPSetScissor = 61,
    gfxd_DPSetScissorFrac = 62,
    gfxd_DPSetTextureDetail = 63,
    gfxd_DPSetTextureFilter = 64,
    gfxd_DPSetTextureLOD = 65,
    gfxd_DPSetTextureLUT = 66,
    gfxd_DPSetTexturePersp = 67,
    gfxd_DPSetTile = 68,
    gfxd_DPSetTileSize = 69,
    gfxd_SP1Triangle = 70,
    gfxd_SP2Triangles = 71,
    gfxd_SP1Quadrangle = 72,
    gfxd_SPBranchLessZraw = 73,
    gfxd_SPBranchList = 74,
    gfxd_SPClipRatio = 75,
    gfxd_SPCullDisplayList = 76,
    gfxd_SPDisplayList = 77,
    gfxd_SPEndDisplayList = 78,
    gfxd_SPFogFactor = 79,
    gfxd_SPFogPosition = 80,
    gfxd_SPForceMatrix = 81,
    gfxd_SPSetGeometryMode = 82,
    gfxd_SPClearGeometryMode = 83,
    gfxd_SPLoadGeometryMode = 84,
    gfxd_SPInsertMatrix = 85,
    gfxd_SPLine3D = 86,
    gfxd_SPLineW3D = 87,
    gfxd_SPLoadUcode = 88,
    gfxd_SPLookAtX = 89,
    gfxd_SPLookAtY = 90,
    gfxd_SPLookAt = 91,
    gfxd_SPMatrix = 92,
    gfxd_SPModifyVertex = 93,
    gfxd_SPPerspNormalize = 94,
    gfxd_SPPopMatrix = 95,
    gfxd_SPPopMatrixN = 96,
    gfxd_SPSegment = 97,
    gfxd_SPSetLights1 = 98,
    gfxd_SPSetLights2 = 99,
    gfxd_SPSetLights3 = 100,
    gfxd_SPSetLights4 = 101,
    gfxd_SPSetLights5 = 102,
    gfxd_SPSetLights6 = 103,
    gfxd_SPSetLights7 = 104,
    gfxd_SPNumLights = 105,
    gfxd_SPLight = 106,
    gfxd_SPLightColor = 107,
    gfxd_SPTexture = 108,
    gfxd_SPTextureRectangle = 109,
    gfxd_SPTextureRectangleFlip = 110,
    gfxd_SPVertex = 111,
    gfxd_SPViewport = 112,
    gfxd_DPLoadTLUTCmd = 113,
    gfxd_DPLoadTLUT = 114,
    gfxd_BranchZ = 115,
    gfxd_DisplayList = 116,
    gfxd_DPHalf1 = 117,
    gfxd_DPHalf2 = 118,
    gfxd_DPWord = 119,
    gfxd_DPLoadTile = 120,
    gfxd_SPGeometryMode = 121,
    gfxd_SPSetOtherMode = 122,
    gfxd_SPSetOtherModeLo = 123,
    gfxd_SPSetOtherModeHi = 124,
    gfxd_DPSetOtherMode = 125,
    gfxd_MoveWd = 126,
    gfxd_MoveMem = 127,
    gfxd_SPDma_io = 128,
    gfxd_SPDmaRead = 129,
    gfxd_SPDmaWrite = 130,
    gfxd_LoadUcode = 131,
    gfxd_SPLoadUcodeEx = 132,
    gfxd_TexRect = 133,
    gfxd_TexRectFlip = 134,
    gfxd_SPNoOp = 135,
    gfxd_Special3 = 136,
    gfxd_Special2 = 137,
    gfxd_Special1 = 138,
}
